# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build-Test-Deploy

on:
  push:
    branches: [ master ]

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    name: Making builds
    steps:
    - uses: actions/checkout@v2
    - name: Install surge
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g surge
