# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    name: Making builds
    steps:
    - uses: actions/checkout@v2
    - name: Install surge
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g surge
    
  Test-job1:
    runs-on: ubuntu-latest
    name: Test1
    needs: Build-Job
    if: github.rev != 'refs/heads/production'
    steps:
      - uses: action/checkout@v1
      - name: Test1
        uses: actions/setup/node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - run: npm install --global mocha
      - run: npm test
  Test-job3:
    runs-on: ubuntu-latest
    needs: Build-Job
    if: github.ref != 'refs/heads/production'
    name: Test3
    steps:
      - uses: actions/checkout@v1
      - name: Test3
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha
      - run: npm install unit.js
      - run: npm test
      
  Deploy-Job:
    runs-on: ubuntu-latest
    needs: [Test-job1, Test-job3]
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: Test3
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: surge ./ ${{secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      


